import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "../globals.css";
import Navbar from "../components/businessDashboard/Navbar";
import Sidebar from "../components/businessDashboard/Sidebar";

const figtree = Figtree({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "appobook",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${figtree.className} flex flex-col`}>
      <Navbar />
      <div className="flex">
        <Sidebar />
        {children}
      </div>
    </div>
  );
}